name: '532'
channels:
  - conda-forge
dependencies:
  - numpy
  - plotly
  - matplotlib
  - pandas
  - python
  - ipykernel
  - seaborn
  - scienceplots
  - scikit-learn
  - nbformat
  - shiny
  - pycountry
  - shinywidgets
  - anywidget
  - chatlas
  - dotenv
  - openai
  - anthropic
  - ollama
  - querychat